FROM node:14-alpine

# set environments
ENV TZ=America/Sao_Paulo
ENV NPM_CONFIG_LOGLEVEL=warn
ENV WORKDIR=/home/node/app
ENV USER=node

# update system and install tz
RUN apk add --update --no-cache bash tzdata python alpine-sdk && \
    rm -rf /var/cache/apk/*

# set non-root user
USER ${USER}

# set workdir
WORKDIR ${WORKDIR}

# create directory app and permission
RUN mkdir -p ${WORKDIR}/node_modules && \
    chown -R ${USER}:${USER} ${WORKDIR}

# copy package.json and yarn lock
COPY --chown=${USER}:${USER} ./package.json ./

# install node dependencies
RUN npm install

# copy all project files to working directory
COPY --chown=${USER}:${USER} ./ ./
#RUN chown -R node:1000 ${WORKDIR}

# run build
RUN npm run build

# expose port
EXPOSE ${PORT:-3333}

# start application
CMD ["npm", "run", "start"]
