FROM node:14-alpine

# set environments
ENV TZ=America/Sao_Paulo
ENV NPM_CONFIG_LOGLEVEL=warn

# set non-root user
USER node

# set workdir
ENV WORKDIR=/home/node/app
WORKDIR ${WORKDIR}

# create directory app and permission
RUN mkdir -p ${WORKDIR}/node_modules && \
    chown -R node:node ${WORKDIR}

# copy package.json and yarn lock
COPY --chown=node:node ./package.json  ./yarn.* ./

# update system and install tz
RUN apk add --update --no-cache bash tzdata python alpine-sdk && rm -rf /var/cache/apk/*

# copy all project files to working directory
COPY --chown=node:node ./ .
RUN chown -R node:1000 ${WORKDIR}

# install node dependencies
RUN yarn install --pure-lockfile --production=true

# expose port
EXPOSE ${PORT:-3333}

# start application
CMD ["npm", "run", "start"]
