# build stage 1
FROM node:16-alpine as builder

ENV NPM_CONFIG_LOGLEVEL=warn

RUN apk add \
  --update \
  --no-cache \
  bash  \
  tzdata  \
  python3  \
  alpine-sdk  \
  && rm -rf /var/cache/apk/*

ENV WORKDIR=/home/app
WORKDIR ${WORKDIR}

COPY ./src ./src
COPY ./.sequelizerc ./
COPY ./tsconfig.json ./
COPY ./package.json yarn.lock ./

RUN yarn install --ignore-scripts --frozen-lockfile --non-interactive --silent
RUN yarn build

# build stage 2
FROM builder as finish

ENV TZ=America/Sao_Paulo
ENV WORKDIR=/home/app
WORKDIR ${WORKDIR}

COPY --from=builder ./home/app/.sequelizerc ./.sequelizerc
COPY --from=builder ./home/app/package.json ./package.json
COPY --from=builder ./home/app/node_modules ./node_modules
COPY --from=builder ./home/app/dist ./dist

EXPOSE ${PORT:-3333}
CMD ["node", "./dist/server/index.js"]
