apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: node-app
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      namespace: node-app
      labels:
        app: backend
    spec:
      serviceAccountName: backend
      containers:
        - name: backend
          image: "IMAGE_NAME:TAG"
          imagePullPolicy: Always
          ports:
            - name: backend
              containerPort: 3333
              protocol: TCP
          envFrom:
            - configMapRef:
                name: backend
          volumeMounts:
            - mountPath: "/storage/uploads"
              name: pvc-backend
      volumes:
        - name: pvc-backend
          persistentVolumeClaim:
            claimName: pvc-backend
