---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: node-app
  labels:
    app: postgres
data:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "root"
  POSTGRES_DB: "development"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      namespace: node-app
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              subPath: data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: pvc-storage
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: node-app
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
