apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-backend
  namespace: node-app
  labels:
    app: pvc-backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
