---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: node-app
  labels:
    app: redis
data:
  REDIS_PASSWORD: "redis"
  ALLOW_EMPTY_PASSWORD: "no"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: node-app
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis
      namespace: node-app
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: redis
          image: bitnami/redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          envFrom:
            - configMapRef:
                name: redis
          volumeMounts:
            - mountPath: /bitnami/redis/data
              subPath: data
              name: redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: pvc-storage
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: node-app
spec:
  selector:
    app: redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      protocol: TCP
