---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: node-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: node-apps
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "services" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend
  namespace: node-apps
subjects:
  - kind: ServiceAccount
    name: backend
    namespace: node-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend
